services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: gate
      POSTGRES_PASSWORD: gate
      POSTGRES_DB: gate
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gate"]
      interval: 10s
      timeout: 5s
      retries: 5

  dex:
    image: ghcr.io/dexidp/dex:latest
    ports:
      - "5556:5556"
    volumes:
      - ./config.yaml:/etc/dex/config.yaml
    depends_on:
      postgres:
        condition: service_healthy
