apiVersion: apps/v1
kind: Deployment
metadata:
  name: gate
  labels:
    app: gate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gate
  template:
    metadata:
      labels:
        app: gate
    spec:
      serviceAccountName: gate
      containers:
        - name: gate
          image: gate:0.0.1
          ports:
            - containerPort: 8080
          imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: gate
spec:
  selector:
    app: gate
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gate
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gate
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gate
subjects:
  - kind: ServiceAccount
    name: gate
    namespace: default
roleRef:
  kind: ClusterRole
  name: gate
  apiGroup: rbac.authorization.k8s.io
