apiVersion: apps/v1
kind: Deployment
metadata:
  name: gate-agent
  labels:
    app: gate-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gate-agent
  template:
    metadata:
      labels:
        app: gate-agent
    spec:
      serviceAccountName: gate-agent
      containers:
        - name: gate-agent
          image: gate/agent:0.0.1
          ports:
            - containerPort: 8080
          imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: gate-agent
spec:
  selector:
    app: gate-agent
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gate-agent
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gate-agent
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gate-agent
subjects:
  - kind: ServiceAccount
    name: gate-agent
    namespace: default
roleRef:
  kind: ClusterRole
  name: gate-agent
  apiGroup: rbac.authorization.k8s.io
