name: CD

on:
  push:
    tags:
    - '*'

jobs:
  deploy:
    strategy:
      matrix:
        app: [proxy, manager]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Docker Build & Push
      uses: docker/build-push-action@v2
      with:
        context: .
        tags: yhc0818/gate/${{ matrix.app }}:${{ github.ref_name }}
        dockerfile: ./docker/${{ matrix.app }}.Dockerfile
        push: true
