name: CI

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go 1.24.2
        uses: actions/setup-go@v4
        with:
          go-version: 1.24.2
      - name: Build
        run: make build
